---
- id: ps_training_morning
  name: Paradigm Shift Training (09:00)
- id: ps_training_before
  name: Paradigm Shift Training (1 hour before start)
- id: ps_training_onevent
  name: Paradigm Shift Training (on start)
