---
kind: pipeline
name: build
type: docker
trigger:
  branch:
    - master

steps:
  - name: build-test
    image: seangenabe/pnpm-alpine
    commands:
      - pnpm install
      - pnpm run build
      - pnpm test
  - name: sonar
    image: saitho/drone-sonar-plugin
    settings:
      sonar_host: https://sonarcloud.io
      sonar_token:
        from_secret: SONAR_TOKEN
      branchAnalysis: false
      enableGateBreaker: true
      inclusions: "src/**/*.ts"
      exclusions: "test/**/*.test.ts"

---
kind: pipeline
name: release
type: docker
trigger:
  branch:
    - master
    - debug
depends_on:
  - build

steps:
  - name: release
    image: saitho/docker-semantic-release
    environment:
      NPM_TOKEN:
        from_secret: npm_token
      GH_TOKEN:
        from_secret: gh_token
      DEBUG: saithodev:semantic-release-gitea
    commands:
      - mkdir -p docs
      - pnpm install
      - pnpx semantic-release